#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width 0
bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a easyeffects desktop='^10' follow=off
bspc rule -a Spotify desktop='^9' follow=off


setxkbmap -option caps:escape
feh --bg-fill /home/angel/Pictures/wtf.webp

/home/angel/.config/polybar/./launch.sh &
/usr/bin/wmname LG3D & 
/usr/bin/picom &
/usr/bin/lxpolkit &
/usr/bin/easyeffects & 
/usr/bin/spotify &
#
# Configurar la tasa de refresco del monitor
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 74.97

